version: 0.2

env:
  variables:
    WAMBDA_DEBUG: "true"
    WAMBDA_USE_MOCK: "false"
    WAMBDA_NO_AUTH: "false"
    WAMBDA_DENY_SIGNUP: "false"
    WAMBDA_DENY_LOGIN: "false"
    WAMBDA_LOG_LEVEL: "DEBUG"
    S3_BUCKET: "hakira0627-s3-wambda-ssr001-main"
    DYNAMODB_TABLE: "table-wambda-ssr001-main"

phases:
  install:
    runtime-versions:
      python: 3.13
  build:
    commands:
      - aws s3 sync static/ s3://$S3_BUCKET/CloudFront/static --delete
      - aws s3 cp favicon/favicon.ico s3://$S3_BUCKET/CloudFront/favicon.ico
      - sam build
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --parameter-overrides ParameterKey=DEBUG,ParameterValue=$WAMBDA_DEBUG ParameterKey=UseMock,ParameterValue=$WAMBDA_USE_MOCK ParameterKey=NoAuth,ParameterValue=$WAMBDA_NO_AUTH ParameterKey=DenySignup,ParameterValue=$WAMBDA_DENY_SIGNUP ParameterKey=DenyLogin,ParameterValue=$WAMBDA_DENY_LOGIN ParameterKey=LogLevel,ParameterValue=$WAMBDA_LOG_LEVEL ParameterKey=DynamoDBTable,ParameterValue=$DYNAMODB_TABLE
